### PR TITLE
feat!: Update deployment to support latest Klyshko features

### PR DESCRIPTION
**Pull request by strieflin**
This requires carbynestack/klyshko#69 to be merged first.

### CODE REVIEW

**Review by sbckr — CHANGES_REQUESTED** [review]
Deployment fails with

```shell
TupleGenerator.klyshko.carbnyestack.io "cs-klyshko-config-tg" is invalid: spec.generator: Required value
```

It seems like Klyshko's crd definition for `TupleGenerator` with properties (focus on `spec`):
```yaml
apiVersion <string>
kind <string>
metadata <object>
spec <object>
    generator <object>
        image <string>
        imagePullPolicy <string>
    supports <array>
```

does not match the go struct declaration for `TupleGeneratorSpec`:
```go
// TupleGeneratorSpec defines the desired state of TupleGenerator.
type TupleGeneratorSpec struct {

	// Template is used to instantiate the pod for TupleGenerationTask instances generated for this TupleGenerator.
	Template TupleGeneratorPodTemplateSpec `json:"template"`

	//+kubebuilder:validation:MinItems=1
	// Supports specifies which tuples can be generated by this Generator.
	Supports []TupleTypeSpec `json:"supports"`
}
```
where `TupleGenerator`'s `spec` would look more like
```yaml
template <object>
    spec <object>
        affinity <object>
        container <object>
            image <string>
            imagePullPolicy <string>
            resources <object>
supports <array>
``` 

`template`<> `generator`

Am I getting it wrong?

**Comment by strieflin** [comment]
You are @sbckr. Somehow the CRD changes in the operator chart got lost. This is addressed by carbynestack/klyshko#89.

**Comment by strieflin** [comment]
Blocked by carbynestack/klyshko#89 and #76.

**Comment by sbckr** [comment]
@strieflin These changes won't affect the IaC based deployment. 
Should we add a default secure CRG configuration for IaC based deployment and a deploy option / parameter available, or do we consider this as an improvement for the future?

**Comment by strieflin** [comment]
> @strieflin These changes won't affect the IaC based deployment. Should we add a default secure CRG configuration for IaC based deployment and a deploy option / parameter available, or do we consider this as an improvement for the future?

See #95 that tracks exactly this.

**Review by sbckr — APPROVED** [review]
LGTM

**Pull request merged**
